### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by fireindark707** [IAmPara0x/Yuno#1]
Hi, I find your work very inspiring and the program code very complete. I would like to learn your special way of training. It looks like you used an unsupervised approach (maybe called Pair-based metric learning) to train the model to learn semantics. I am curious how pos, neg and anchor are selected. I'm still reading the code. I haven't fully understood it yet.

According to my understanding, the comments of the same anime are set as anchor and pos, while the comments of any other randomly selected anime are defined as neg

**Comment by IAmPara0x** [comment]
You can learn how about training method and about the loss function [here](https://medium.com/@confusedstudent13/yuno-context-based-search-engine-for-anime-39f5cb86f845) .

> According to my understanding, the comments of the same anime are set as anchor and pos, while the comments of any other randomly selected anime are defined as neg

Not all reviews were selected as "neg" . Only reviews from animes that are **not similar** to the current anime.

And **not similar** animes are those that don't share any kinds of genres between them.

Example:

    1. Yona of the dawn has following genres: Action, Adventure, Comedy, Drama, Fantasy, Romance.
    2. takt op Destiny has following genres: Action, Music, Fantasy.
    3. My Teen Romantic Comedy (Oregairu) has following genres: Comedy, Drama, Romance, Slice of Life.

According to the definition _takt op Destiny_ will not be similar to _My Teen Romantic Comedy_ . But that doesn’t mean _Yona of the dawn_ is similar to _takt op Destiny_ there is no relation defined between objects oᵢ and oⱼ where sᵢ ∩ sⱼ ≠ ∅ and i ≠ j. The only anime that _takt op Destiny_ is similar to is itself.
 
And, here's the training notebook with all the parameters: https://www.kaggle.com/iamparadox/yuno-models

**Comment by fireindark707** [comment]
Thanks for your response!
