### ISSUE TITLE
Pipfile execute falsely

### ISSUE THREAD

**Issue by Chaopeng-Wu** [IAmPara0x/Yuno#2]
Cannot run program "D:\PythonProject\Yuno\Pipfile" (in directory "D:\PythonProject\Yuno"): CreateProcess error=193, %1 It isn't available Win32  Application。
![image](https://user-images.githubusercontent.com/51105048/146414752-6265e721-0003-4b0b-b0f2-c72e7c9340fa.png)

**Comment by IAmPara0x** [comment]
Hey, please use `pip install -r requirements.txt` if pipenv is not working. BTW if you are trying to run the search engine locally you would need to download [search base](https://www.kaggle.com/sahilbannoo/yuno-search-data)
