### ISSUE TITLE
synopsis might a better source

### ISSUE THREAD

**Issue by koke2c95** [IAmPara0x/Yuno#3]
good job!
but result seem not so good.

I know many Recommendation Systems based on **movie entity graph (meta data)** and **user comment (based on NLP)**

and I think you can give it a try on synopsis [(japanese article) reference from this](https://kirarajump-tech.hatenablog.com/entry/2021/12/12/112218)

and I just discovered tmdb can be a good source , seem English synopsis edit almost on every anime entity, and its parallel multilingual text
some well-known example:
[Story synopsis](https://www.themoviedb.org/tv/83121/translations) - [API](https://developers.themoviedb.org/3/tv/get-tv-translations)
[epsiode synopsis](https://www.themoviedb.org/tv/42916-toradora/season/1/episode/1/translations) or [interface language mode=ja-JP](https://www.themoviedb.org/tv/42916-toradora/season/1/episode/1?language=ja-JP) - [API](https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-translations)

if Interested on multilingual [sbert multilingual model](https://www.sbert.net/docs/pretrained_models.html)

I didn't found who build a Parallel text dataset or dump with translations [dev reference](https://www.themoviedb.org/talk/54f41aafc3a3683455000991)
you can use [discover API to get anime tv/moive id](https://developers.themoviedb.org/3/discover/tv-discover)

**Comment by IAmPara0x** [comment]
Hey, thanks a lot for the suggestion about the episode synopsis, I didn't knew about it. I will definitely try to use this in the future version of Yuno. And can you tell me some queries that were giving you bad results, because I am really curious of why it is happening.
