### ISSUE TITLE
kaggle colab does not work

### ISSUE THREAD

**Issue by ghost** [IAmPara0x/Yuno#6]
I get this error everytime 
```ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-4604c83e7d7e> in <module>
      1 import dill as pickle
----> 2 from yuno.search import pipelines,base,config,utils
      3 import torch
      4 import torch.nn.functional as F
      5 import faiss

ModuleNotFoundError: No module named 'yuno'
```

**Comment by IAmPara0x** [comment]
@toprak I just tested it on kaggle and it seems to be working. I also tested the following query:

```
Query: anime with great plot where there's good chemistry between male and female MC

Results: 
               1. SAO
               2. Dan machi
               3. oresuki
```

The only thing I think could be going wrong is you might have disabled the internet in the notebook.

**Comment by ghost** [comment]
@IAmPara0x I have no experience on kaggle but I just clicked to copy and edit and I just clicked run all on run section
I get this everytime, I am searching web to enable internet stuff (I dont know I am disabled it)
```ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cfd3f8ca369a> in <module>
      5 
      6 import dill as pickle
----> 7 from yuno.search import pipelines,base,config,utils
      8 import torch
      9 import torch.nn.functional as F

ModuleNotFoundError: No module named 'yuno'
```

**Comment by ghost** [comment]
also its same on google colab too

**Comment by IAmPara0x** [comment]
That's strange. Could you insert the new cell and then run the following command:
```shell
!git clone https://github.com/IAmPara0x/Yuno.git
```
and let me know what it says.

**Comment by ghost** [comment]
I got
```Cloning into 'Yuno'...
fatal: unable to access 'https://github.com/IAmPara0x/Yuno.git/': Could not resolve host: github.com
```
I found this on internet but did not work, I will look other possible solution
![image](https://github.com/IAmPara0x/Yuno/assets/43301560/28513b0e-ce0c-4ccf-be5d-0733d7bea1d0)

**Comment by IAmPara0x** [comment]
Your notebook has internet access, but it's not able to resolve the URL (which is very strange). BTW have you setup the 2 factor auth with kaggle it seems like you didn't because your notebook doesn't have any accelerator (i.e. GPU).

**Comment by ghost** [comment]
@IAmPara0x ah yeah did it as you said now its working thanks! I just wonder what does increasing or decreasing curiosity

**Comment by snowman** [comment]
![image](https://github.com/IAmPara0x/Yuno/assets/16096559/8b096dee-4e3c-4509-abac-14983eaddf51)


do *NOT* use latest environment
