### ISSUE TITLE
Google colab notebook error 

### ISSUE THREAD

**Issue by AbdulrahmanIII** [IAmPara0x/Yuno#8]
FileNotFoundError: [Errno 2] No such file or directory: 'search_base.pkl'

And

NameError: name 'pipeline' is not defined

**Comment by IAmPara0x** [comment]
Hey, I recommend you to try kaggle version of Yuno: https://www.kaggle.com/code/iamparadox/yunoo. It's more stable and provides faster search result. The only downside is you must create a kaggle account (which you can as it's free)

I have just tested the kaggle version and it's working fine.

**Comment by AbdulrahmanIII** [comment]
> Hey, I recommend you to try kaggle version of Yuno: https://www.kaggle.com/code/iamparadox/yunoo. It's more stable and provides faster search result. The only downside is you must create a kaggle account (which you can as it's free)

I did 2 days ago,  thank you it's an awesome way to find anime
Solved. BTW can you like update it or teach us how!
Well done.

**Comment by IAmPara0x** [comment]
>  Solved. BTW can you like update it or teach us how!

Yup, I am planning to update it and adding more features to it very soon!
